pipeline {
    agent any

    environment {
        COMPOSE_PROJECT_NAME = "edadocker"
    }


    stages {
        stage("docker login"){
            steps{

                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USR', passwordVariable: 'DOCKER_PASS')]){
                    script{

                        sh "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USR} --password-stdin"

                    }
                }

            }
        }
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/MantoshDas/Heart-Disease-using-EDA.git'
            }
        }

        stage('Install Docker Compose (if needed)') {
            steps {
                sh '''
                if ! command -v docker-compose &> /dev/null
                then
                    echo "Installing Docker Compose..."
                    sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose
                fi
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('EDADocker') {
                    sh 'docker-compose build'
                }
            }
        }
        stage("Push to docker hub"){
            steps{
                echo "Pushing to docker hub"

                sh "docker tag edadocker mann11/edadocker:latest"

                sh "docker push mann11/edadocker:latest"

            }
        }


        stage('Run Docker Container') {
            steps {
                dir('EDADocker') {
                    sh 'docker-compose up -d'
                }
            }
        }

        stage('Verify Container') {
            steps {
                sh 'docker ps -a'
            }
        }
    }

    post {
        always {
            dir('EDADocker') {
                sh 'docker-compose down'
            }
        }
    }
}
